#!/usr/bin/env python3
"""Generate OUTLINE.md: the wiki sidebar tree, with links to local .xwiki files.

Directory names in wiki-content/ are XWiki *space* names ("Main", "sdf"), while
the sidebar shows each page's *display title* ("1. Foundation", "a. Operational
Demands"). This reads the title out of each file's %%WIKI-SYNC-META%% header and
renders a nested list keyed on titles, so the outline reads the way the wiki does.
"""

import re
import sys
from pathlib import Path
from urllib.parse import quote

META_MARK = "%%WIKI-SYNC-META%%"
CONTENT_DIR = Path(__file__).resolve().parent.parent / "wiki-content"
OUT_FILE = CONTENT_DIR.parent / "OUTLINE.md"


def read_title(path: Path) -> str:
    """Pull `title:` from the sync meta header, falling back to the file stem."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return path.stem
    if not text.startswith(META_MARK + "\n"):
        return path.stem
    rest = text[len(META_MARK) + 1:]
    idx = rest.find("\n" + META_MARK)
    if idx == -1:
        return path.stem
    for line in rest[:idx].split("\n"):
        if line.startswith("title:"):
            return line.split(":", 1)[1].strip() or path.stem
    return path.stem


def sort_key(title: str):
    """Natural sort: split digit runs out so "2." precedes "10.", case-insensitive.

    Numbers compare as ints and sort ahead of text at the same position, so
    "0. Intro" < "1. Foundation" < "2. Specification" < "a. Quickstart".
    """
    parts = re.split(r"(\d+)", title)
    key = []
    for part in parts:
        if not part:
            continue
        if part.isdigit():
            key.append((0, int(part), ""))
        else:
            key.append((1, 0, part.lower()))
    return key


def link(label: str, path: Path) -> str:
    rel = path.relative_to(OUT_FILE.parent).as_posix()
    # Escape ] in labels so the markdown link target is not truncated.
    label = label.replace("[", "\\[").replace("]", "\\]")
    return f"[{label}]({quote(rel)})"


def walk(directory: Path, depth: int, lines: list):
    """Emit one list item per page, recursing into subspaces.

    Entries are ordered by display title rather than by space name, since the
    two often disagree (space "b. Design Scenario" has title "a1. Design
    Scenario"). A space with no WebHome falls back to its directory name.
    """
    # A space's own page is WebHome.xwiki; other .xwiki files are leaf pages.
    entries = []
    for child in directory.iterdir():
        if child.name.endswith(".attachments"):
            continue
        if child.is_dir():
            home = child / "WebHome.xwiki"
            title = read_title(home) if home.exists() else child.name
            entries.append((title, child, home if home.exists() else None))
        elif child.suffix == ".xwiki" and child.stem != "WebHome":
            entries.append((read_title(child), child, child))

    entries.sort(key=lambda e: sort_key(e[0]))

    for title, entry, page in entries:
        indent = "  " * depth
        if entry.is_dir():
            if page is not None:
                lines.append(f"{indent}- {link(title, page)}")
            else:
                # Space with no page of its own; show the bare name as a group.
                lines.append(f"{indent}- {title}")
            walk(entry, depth + 1, lines)
        else:
            lines.append(f"{indent}- {link(title, page)}")


def main():
    if not CONTENT_DIR.is_dir():
        print(f"No wiki-content directory at {CONTENT_DIR}", file=sys.stderr)
        return 1

    lines = [
        "# Wiki Outline",
        "",
        "Generated by `wiki-sync/outline.py` -- do not edit by hand.",
        "Titles are the wiki's display names; links point at the local files,",
        "whose directories are named after XWiki spaces.",
        "",
    ]
    walk(CONTENT_DIR, 0, lines)
    lines.append("")

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    count = sum(1 for line in lines if line.lstrip().startswith("- "))
    print(f"Wrote {OUT_FILE} ({count} entries).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
